### ISSUE TITLE
I need some help to update Charry shortcodes

### ISSUE THREAD

**Issue by jernejd** [CherryFramework/cherry-shortcodes#6]
Dear Sirs,

Would you be so kind to help me, please? As I can't automatically update Charry shortcodes plugin from version 1.0.7.2 to 1.0.7.3 I downloaded the zip file from https://github.com/CherryFramework/cherry-shortcodes/releases/v1.0.7.3, uploaded manually to the server, but still face problems. 

Why at first I receive the message that the update is successfully updated http://prntscr.com/ajtmgj, but when I refresh the Admin panel there is again the message to update http://prntscr.com/ajtncq

I tried to update this plugin at least 15 times.

Thank you very much in advance.

Kind regards

Jernej

**Comment by ghost** [comment]
@jernejd, hello!

It seems that you have same issue as #5.
Please try to download the latest version of the plugin (1.0.7.4).

**Comment by jernejd** [comment]
Thank you soo much, wonderful, works well now.
Thank you @dkfiresky again for really quick and useful support.
Have a nice w/e
Jernej
