### ISSUE TITLE
Video Preview and YouTube Videos

### ISSUE THREAD

**Issue by jvivona** [CherryFramework/cherry-shortcodes#7]
Running shortcodes plugin 1.0.7.6 - when I put a video_preview shortcode in using a YouTube URL - I get no "video" and I get a javascript error in  "cannot read property getPLayerState of undefined".

If I use a video in the Media Manager, shortcode works as expected.    Any advice or tips?

This is the shortcode I am using:  [cherry_video_preview source="http://www.youtube.com/watch?v=Gt2e2BWlSsA" preload="yes"]View Video[/cherry_video_preview]

**Comment by ghost** [comment]
@jvivona can you please provide more information on the problem (example: browser you're using).

The error you get can't be reproduced, as there is no `getPLayerState` method or property used in the code, though there is `getPlayerState` method call [here](https://github.com/CherryFramework/cherry-shortcodes/blob/master/assets/js/shotcodes/video-preview.js#L176) but it works fine.

**Comment by jvivona** [comment]
you are correct.  I mistyped the function name with an extra capital letter.

I'm going to try and build a standalone page with the minimum pieces to reproduce.

**Comment by bhuveh** [comment]
Hi! Was this fixed? I am having the same issue with YouTube URLs as well. Vimeo URLs and Media uploads work fine!
