### ISSUE TITLE
Cherry Sharing

### ISSUE THREAD

**Issue by gigito78** [CherryFramework/cherry-shortcodes#9]
Hello, using cherry sharing shortcode in a page or post cause motopress content editor to crash, it's possible to fix this?

Thanks, Luigi

**Comment by ghost** [comment]
@gigito78 thanks for your report. We will investigate the issue and fix it as soon as possible.

**Comment by ghost** [comment]
This issue will be addressed to the [Cherry Social](https://github.com/CherryFramework/cherry-social) plugin.
